// Import global CSS styles
import '../globals.css';

// Import required modules
import Link from "next/link";
import { getPages } from '@/sanity/sanity-utils';

// Define metadata for the site
export const metadata = {
  title: 'My Awesome Site',
  description: 'Generated by Next + Sanity',
}

// Define the RootLayout component
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Fetch pages data asynchronously
  const pages = await getPages();

  return (
    <html lang="en">
      <body style={{  
        backgroundPosition: 'center center', 
        backgroundSize: 'cover', 
        height: '100vh', 
        margin: 0, 
        padding: 0 
      }}>
        <div className="hero-section bg-gradient-to-r from-gray-900 via-indigo-200 to-blue-200 text-black py-16">
          {/* Add inline CSS for the hero section */}
          <style>
            {`
              /* Force the Hero Section to span the entire width of the screen */
              .hero-section {
                width: 100vw;
                margin-left: calc(-50vw + 50%);
                margin-right: calc(-50vw + 50%);
              }
            `}
          </style>
          <div className="container mx-auto text-center" style={{ 
            backgroundImage: 'url("375208288_686603562977098_3186213666988680908_n.jpg")', 
            backgroundPosition: 'right right', 
            backgroundRepeat: 'no-repeat', 
            minHeight: '200px' 
          }}>
            <div className="mx-auto text-left max-w-md">
              <h1 className="text-7xl font-extrabold">
                Hello, I&apos;m
                <span className="bg-gradient-to-r from-blue-400 via-red-500 to-indigo-600  bg-clip-text text-transparent"> David</span>
              </h1>
              <p className="mt-3 text-sm bg-gradient-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
                {/* Add a description */}
                I am a dedicated Software Engineer based in Orlando, FL, with a strong educational foundation in Computer Engineering from the University of Central Florida, where I earned an ABET Accredited Bachelors degree. My professional journey has been marked by significant accomplishments. In my current role as a Data Engineer at FreeCast, I have honed my skills in HTML, JavaScript, SQL, Python, Kotlin, Android Studio, Node.js, and AWS. At FreeCast, I have developed Python algorithms for data scraping, implemented deep links for improved user experiences, and created an ADB tool for debugging Android devices. My expertise also extends to database management, machine learning, and cloud-based solutions. In addition to my professional experience, I have an impressive portfolio of projects, including a full-stack portable microscope application Cell-Gazer, where I utilized the MERN stack and integrated the Sharp library for advanced video editing capabilities. I also created a scheduling app Scheduler that facilitated communication between teachers and students. With a passion for innovation and a track record of excellence, I am a seasoned Software Engineer poised to excel in the field.
              </p>
            </div>
          </div>
        </div>
        <header className="flex items-center justify-between">
          {/* Add a link to the homepage */}
          <Link href="/" className="bg-gradient-to-r from-blue-400 via-red-500 to-indigo-600  bg-clip-text text-transparent"></Link>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
